### ISSUE TITLE
iPad / Discord Link in top of page.

### ISSUE THREAD

**Issue by litecave** [Fl1pNatic/spwnrun#9]
![5B9289B2-6946-451B-A1A1-ED326980EE9C](https://user-images.githubusercontent.com/64094645/137593956-577ffcc8-966a-4667-b26c-f0d266b94b8e.png)

Lol idk how

**Comment by sertdfyguhi** [comment]
hmmmm ```
<meta property="og:description" content="Leaderboards for the SPWN Speedrunning Association. Discord server: <a href="https://discord.gg/amgmf5957T">https://discord.gg/amgmf5957T</a>" />
```

**Comment by litecave** [comment]
idk

**Comment by litecave** [comment]
> hmmmm ``` <meta property="og:description" content="Leaderboards for the SPWN Speedrunning Association. Discord server: https://discord.gg/amgmf5957T" />

Lol

**Comment by Megarion** [comment]
> hmmmm
> 
> ```
> <meta property="og:description" content="Leaderboards for the SPWN Speedrunning Association. Discord server: <a href="https://discord.gg/amgmf5957T">https://discord.gg/amgmf5957T</a>" />
> ```

ok who put that there

**Comment by sertdfyguhi** [comment]
i put that description
